# Generated by Django 5.0.6 on 2024-07-06 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Address', models.CharField(blank=True, max_length=200, null=True)),
                ('Phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('place_of_birth', models.CharField(blank=True, max_length=100, null=True)),
                ('sex', models.CharField(blank=True, max_length=10, null=True)),
                ('civil_status', models.CharField(blank=True, max_length=20, null=True)),
                ('height_m', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('blood_type', models.CharField(blank=True, max_length=10, null=True)),
                ('gsis_no', models.CharField(blank=True, max_length=20, null=True)),
                ('pagibig_no', models.CharField(blank=True, max_length=20, null=True)),
                ('philhealth_no', models.CharField(blank=True, max_length=20, null=True)),
                ('sss_no', models.CharField(blank=True, max_length=20, null=True)),
                ('tin_no', models.CharField(blank=True, max_length=20, null=True)),
                ('spouse_surname', models.CharField(blank=True, max_length=100, null=True)),
                ('spouse_first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('spouse_middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('spouse_name_ext', models.CharField(blank=True, max_length=10, null=True)),
                ('spouse_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('spouse_employer', models.CharField(blank=True, max_length=100, null=True)),
                ('spouse_business_address', models.CharField(blank=True, max_length=200, null=True)),
                ('spouse_telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('child1', models.CharField(blank=True, max_length=100, null=True)),
                ('child2', models.CharField(blank=True, max_length=100, null=True)),
                ('child3', models.CharField(blank=True, max_length=100, null=True)),
                ('child4', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
