# Generated by Django 5.0.6 on 2024-07-17 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Phone',
            new_name='phone',
        ),
    ]
