# Generated by Django 5.0.6 on 2024-07-22 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_phone_item_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Address',
            new_name='address',
        ),
    ]
